name: CI/CD Frontend

on:
  push:
    branches:
      - deploy   # Se activa solo en la rama deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t sheloarkham/tienda-frontend:latest .

      - name: Push image to DockerHub
        run: docker push sheloarkham/tienda-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull sheloarkham/tienda-frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 3000:80 sheloarkham/tienda-frontend:latest
